parameters:
  env(APP_ENV): dev

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/*"
    exclude: "../src/{Kernel.php}"

  App\Action\:
    resource: '../src/Action'
    tags: ['controller.service_arguments']

  Linio\Component\Database\DatabaseManager:
    calls:
      - method: addConnection
        arguments:
          - '%env(DB_DRIVER)%'
          - host: '%env(DB_HOST)%'
            port: '%env(DB_PORT)%'
            dbname: '%env(DB_NAME)%'
            username: '%env(DB_USERNAME)%'
            password: '%env(DB_PASSWORD)%'
            pdo_attributes:
              '!php/const PDO::ATTR_ERRMODE': !php/const PDO::ERRMODE_EXCEPTION

  Crawler\Configuration:
    arguments:
      - types: { json: App\Crawler\CustomType\JsonType }

  Crawler\DocumentBuilder:
    arguments:
      - '@Crawler\Configuration'

  GuzzleHttp\Client: ~

  GuzzleHttp\ClientInterface: '@GuzzleHttp\Client'
